version: '3.5'

services:
  mu_hub_main:
    image: postgres:14.5-alpine
    container_name: mu_hub_main
    restart: always
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=admin
    ports:
      - 5432:5432