version: '3.5'
name: MuHub

services:
  mu_hub_main:
    image: postgres:14.5
    container_name: mu_hub_main
    restart: always
    environment:
      - POSTGRES_DB=mu_hub_main
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=admin
    ports:
      - 5432:5432
    volumes:
      - mu_hub_main_data:/var/lib/postgresql/data

  mu_hub_identity_provider:
    image: postgres:14.5
    container_name: mu_hub_identity_provider
    restart: always
    environment:
      - POSTGRES_DB=mu_hub_identity_provider
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=admin
    ports:
      - 5433:5432
    volumes:
      - mu_hub_identity_provider_data:/var/lib/postgresql/data

  scheduler:
    image: postgres:14.5
    container_name: scheduler
    restart: always
    environment:
      - POSTGRES_DB=scheduler
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=admin
    ports:
      - 5434:5432
    volumes:
      - scheduler_data:/var/lib/postgresql/data

volumes:
  mu_hub_main_data:
  mu_hub_identity_provider_data:
  scheduler_data:
