version: '3.5'
name: MuHub

services:
  mu_hub_main:
    image: postgres:14.5
    container_name: mu_hub_main
    restart: always
    environment:
      - POSTGRES_DB=mu_hub_main
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=admin
    ports:
      - 5432:5432

  mu_hub_identity_provider:
    image: postgres:14.5
    container_name: mu_hub_identity_provider
    restart: always
    environment:
      - POSTGRES_DB=mu_hub_identity_provider
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=admin
    ports:
      - 5433:5432
    
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
    ports:
      - 9200:9200
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    environment:
      - xpack.monitoring.enabled=true
      - xpack.watcher.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    networks:
      - elastic

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.9.2
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_URL=http://localhost:9200
    networks:
      - elastic

networks:
  elastic:
    driver: bridge

volumes:
  elasticsearch-data: